"""CodeRelation table — identical to gitnexus schema.js lines 176-356."""
from __future__ import annotations

RELATION_SCHEMA = """CREATE REL TABLE CodeRelation (
  FROM File TO File, FROM File TO Folder, FROM File TO Function, FROM File TO Class,
  FROM File TO Interface, FROM File TO Method, FROM File TO CodeElement,
  FROM File TO `Struct`, FROM File TO `Enum`, FROM File TO `Macro`, FROM File TO `Typedef`,
  FROM File TO `Union`, FROM File TO `Namespace`, FROM File TO `Trait`, FROM File TO `Impl`,
  FROM File TO `TypeAlias`, FROM File TO `Const`, FROM File TO `Static`, FROM File TO `Property`,
  FROM File TO `Record`, FROM File TO `Delegate`, FROM File TO `Annotation`,
  FROM File TO `Constructor`, FROM File TO `Template`, FROM File TO `Module`,
  FROM Folder TO Folder, FROM Folder TO File,
  FROM Function TO Function, FROM Function TO Method, FROM Function TO Class,
  FROM Function TO Community, FROM Function TO `Macro`, FROM Function TO `Struct`,
  FROM Function TO `Template`, FROM Function TO `Enum`, FROM Function TO `Namespace`,
  FROM Function TO `TypeAlias`, FROM Function TO `Module`, FROM Function TO `Impl`,
  FROM Function TO Interface, FROM Function TO `Constructor`, FROM Function TO `Const`,
  FROM Function TO `Typedef`, FROM Function TO `Union`, FROM Function TO `Property`,
  FROM Class TO Method, FROM Class TO Function, FROM Class TO Class, FROM Class TO Interface,
  FROM Class TO Community, FROM Class TO `Template`, FROM Class TO `TypeAlias`,
  FROM Class TO `Struct`, FROM Class TO `Enum`, FROM Class TO `Annotation`,
  FROM Class TO `Constructor`, FROM Class TO `Trait`, FROM Class TO `Macro`,
  FROM Class TO `Impl`, FROM Class TO `Union`, FROM Class TO `Namespace`, FROM Class TO `Typedef`,
  FROM Method TO Function, FROM Method TO Method, FROM Method TO Class, FROM Method TO Community,
  FROM Method TO `Template`, FROM Method TO `Struct`, FROM Method TO `TypeAlias`,
  FROM Method TO `Enum`, FROM Method TO `Macro`, FROM Method TO `Namespace`,
  FROM Method TO `Module`, FROM Method TO `Impl`, FROM Method TO Interface,
  FROM Method TO `Constructor`, FROM Method TO `Property`,
  FROM `Template` TO `Template`, FROM `Template` TO Function, FROM `Template` TO Method,
  FROM `Template` TO Class, FROM `Template` TO `Struct`, FROM `Template` TO `TypeAlias`,
  FROM `Template` TO `Enum`, FROM `Template` TO `Macro`, FROM `Template` TO Interface,
  FROM `Template` TO `Constructor`, FROM `Module` TO `Module`,
  FROM CodeElement TO Community, FROM Interface TO Community, FROM Interface TO Function,
  FROM Interface TO Method, FROM Interface TO Class, FROM Interface TO Interface,
  FROM Interface TO `TypeAlias`, FROM Interface TO `Struct`, FROM Interface TO `Constructor`,
  FROM `Struct` TO Community, FROM `Struct` TO `Trait`, FROM `Struct` TO `Struct`,
  FROM `Struct` TO Class, FROM `Struct` TO `Enum`, FROM `Struct` TO Function,
  FROM `Struct` TO Method, FROM `Struct` TO Interface,
  FROM `Enum` TO `Enum`, FROM `Enum` TO Community, FROM `Enum` TO Class, FROM `Enum` TO Interface,
  FROM `Macro` TO Community, FROM `Macro` TO Function, FROM `Macro` TO Method,
  FROM `Module` TO Function, FROM `Module` TO Method,
  FROM `Typedef` TO Community, FROM `Union` TO Community,
  FROM `Namespace` TO Community, FROM `Namespace` TO `Struct`,
  FROM `Trait` TO Community, FROM `Impl` TO Community, FROM `Impl` TO `Trait`,
  FROM `Impl` TO `Struct`, FROM `Impl` TO `Impl`,
  FROM `TypeAlias` TO Community, FROM `TypeAlias` TO `Trait`, FROM `TypeAlias` TO Class,
  FROM `Const` TO Community, FROM `Static` TO Community, FROM `Property` TO Community,
  FROM `Record` TO Community, FROM `Delegate` TO Community, FROM `Annotation` TO Community,
  FROM `Constructor` TO Community, FROM `Constructor` TO Interface, FROM `Constructor` TO Class,
  FROM `Constructor` TO Method, FROM `Constructor` TO Function, FROM `Constructor` TO `Constructor`,
  FROM `Constructor` TO `Struct`, FROM `Constructor` TO `Macro`, FROM `Constructor` TO `Template`,
  FROM `Constructor` TO `TypeAlias`, FROM `Constructor` TO `Enum`, FROM `Constructor` TO `Annotation`,
  FROM `Constructor` TO `Impl`, FROM `Constructor` TO `Namespace`, FROM `Constructor` TO `Module`,
  FROM `Constructor` TO `Property`, FROM `Constructor` TO `Typedef`,
  FROM `Template` TO Community, FROM `Module` TO Community,
  FROM File TO Contributor,
  FROM Function TO Process, FROM Method TO Process, FROM Class TO Process,
  FROM Interface TO Process, FROM `Struct` TO Process, FROM `Constructor` TO Process,
  FROM `Module` TO Process, FROM `Macro` TO Process, FROM `Impl` TO Process,
  FROM `Typedef` TO Process, FROM `TypeAlias` TO Process, FROM `Enum` TO Process,
  FROM `Union` TO Process, FROM `Namespace` TO Process, FROM `Trait` TO Process,
  FROM `Const` TO Process, FROM `Static` TO Process, FROM `Property` TO Process,
  FROM `Record` TO Process, FROM `Delegate` TO Process, FROM `Annotation` TO Process,
  FROM `Template` TO Process, FROM CodeElement TO Process,
  type STRING, confidence DOUBLE, reason STRING, step INT32
)"""
